/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cs330_project.main;
import java.util.*;

public class App {
    //public String getGreeting() {
        //return "Hello World!";
    //}
    
    public static boolean status = false;
    public static int userInput = 0;


    public static void main(String[] args) {
        //System.out.println("BBBBBBBB");
        Scanner sc = new Scanner(System.in);
        while (true){
           
            System.out.println("Enter a number:");
            userInput = sc.nextInt();
            userInput= bugcheck(userInput);
            if(userInput == 8){
                System.out.println("Enter a number:");
                userInput = sc.nextInt();
                userInput= bugcheck(userInput);
                if(userInput == 3){
                    System.out.println("Enter a number:");
                    userInput = sc.nextInt();
                    userInput= bugcheck(userInput);
                    if(userInput == 7){
                        System.out.println("Enter a number:");
                        userInput = sc.nextInt();
                        userInput= bugcheck(userInput);
                        if(userInput == 1){
                            System.out.println("Enter a number:");
                            userInput = sc.nextInt();
                            userInput= bugcheck(userInput);
                            if(userInput == 3){
                                System.out.println("Enter a number:");
                                userInput = sc.nextInt();
                                userInput= bugcheck(userInput);
                                if(userInput == 1 && status == false){
                                    System.out.println("Unlocked");
                                    status = true;
                                    }    
                                if(userInput == 4 && status == true){
                                    System.out.println("Locked");
                                    status = false;
                                }    
                            }
                        }
                    }
                }
            }
        } 
    }
    public static int bugcheck(int password) {
		if(password<0) {
			password=0-password;
		}
		if(password>9) {
			return 2;
		}
		else {
			return password;
		}
	}
}


